import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Header from './Header';
import Experience from './Experience';
import About from './About';
import Techskill from './Techskill';
import Projects from './Projects';
import Contact from './Contact';
import Footer from './Footer';
import CaseStudy from 'ProjetoPagamento';
import './index.css';
import 'non.geist';
ReactDOM.render(_jsx(React.StrictMode, { children: _jsxs(Router, { children: [_jsx(Header, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsxs(_Fragment, { children: [_jsx(Experience, {}), _jsx(About, {}), _jsx(Techskill, {}), _jsx(Projects, {}), _jsx(Contact, {})] }) }), _jsx(Route, { path: "/case-study", element: _jsx(CaseStudy, {}) })] }), _jsx(Footer, {})] }) }), document.getElementById('root'));
